cp index.html teichlehrpfad/start/index.html
cp index.html teichlehrpfad/krebsschere/index.html
cp index.html teichlehrpfad/fische/index.html
cp index.html teichlehrpfad/enten/index.html
cp index.html teichlehrpfad/brennnessel-1/index.html
cp index.html teichlehrpfad/brennnessel-2/index.html
cp index.html teichlehrpfad/laubfrosch-1/index.html
cp index.html teichlehrpfad/laubfrosch-2/index.html
cp index.html teichlehrpfad/grasfrosch-1/index.html
cp index.html teichlehrpfad/grasfrosch-2/index.html
cp index.html teichlehrpfad/molche/index.html
cp index.html teichlehrpfad/libellen/index.html
cp index.html teichlehrpfad/auwald/index.html
cp index.html teichlehrpfad/totholz/index.html
cp index.html teichlehrpfad/spechte/index.html
cp index.html teichlehrpfad/baumhoehlen/index.html
cp index.html teichlehrpfad/unordnung/index.html
cp index.html teichlehrpfad/vielfalt/index.html
cp index.html teichlehrpfad/erdkroete-1/index.html
cp index.html teichlehrpfad/erdkroete-2/index.html
cp index.html teichlehrpfad/teichhuhn/index.html
cp index.html teichlehrpfad/schwamm/index.html
cp index.html teichlehrpfad/teich-1/index.html
cp index.html teichlehrpfad/teich-2/index.html
